TARG=\
	contain

OFILES=\
	${TARG}.$O\
	console.$O\
	map.$O\
	mount.$O\
	util.$O\

<$root/src/mkcmd

TARG=\
	inject

OFILES=\
	${TARG}.$O\
	map.$O\
	util.$O\

<$root/src/mkcmd

TARG=\
	pseudo

OFILES=\
	${TARG}.$O\
	map.$O\
	util.$O\

<$root/src/mkcmd
