pkg=netbsd-curses
ver=0.1.1

url=https://github.com/sabotage-linux/netbsd-curses/archive/v${ver}.tar.gz


<$root/src/mkport

make_install_target=install-static
make_install_args=\
	'INCDIR='$INCDIR\
	'BINDIR='$BINDIR\
	'LIBDIR='$LIBDIR\
