<$root/src/mkconf

LIBS=libopenbsd libz

TARG=grep

LINKS=\
	egrep\
	fgrep\
	zgrep\
	zegrep\
	zfgrep\

OFILES=\
	${TARG}.o\
	binary.o\
	file.o\
	mmfile.o\
	queue.o\
	util.o\

HFILES=\
	grep.h\

<$root/src/mkcmd
