LIBS=libopenbsd

TARG=\
	patch\

OFILES=\
	${TARG}.o\
	backupfile.$O\
	ed.$O\
	inp.$O\
	mkpath.$O\
	pch.$O\
	util.$O\

HFILES=\
	backupfile.h\
	common.h\
	ed.h\
	inp.h\
	pathnames.h\
	pch.h\
	util.h\

<$root/src/mkcmd
